# Generated by Django 4.1.3 on 2022-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_is_sub_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
